# Generated by Django 4.2.4 on 2023-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='undertypes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
