# Generated by Django 4.2.4 on 2023-09-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(max_length=2566, verbose_name='Описание')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('stickers', models.CharField(max_length=255, verbose_name='Стикеры')),
                ('installment', models.BooleanField(default=False, verbose_name='Рассрочка')),
                ('delivery', models.BooleanField(default=False, verbose_name='Доставка')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
