# Generated by Django 4.2.4 on 2023-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя товара')),
                ('price', models.FloatField(max_length=255, verbose_name='Цена товара')),
                ('image_url', models.CharField(max_length=2083)),
                ('rating', models.FloatField(max_length=255, verbose_name='Рекомендация товара')),
                ('description', models.TextField(max_length=255, verbose_name='Описание товара')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
