# Generated by Django 4.2.4 on 2023-09-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_image',
            field=models.CharField(default='Не указано', max_length=2083),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default='Не указано', max_length=255, to='products.category', verbose_name='Категория товара'),
        ),
    ]
